#!/bin/bash
VERSION=$1
OUR_COPY=src/prefect/_vendor/httpx_oauth

rm -Rf /tmp/httpx_oauth
git clone https://github.com/frankie567/httpx-oauth -b $VERSION /tmp/httpx_oauth
rsync -ravP --delete /tmp/httpx_oauth/httpx_oauth/ $OUR_COPY

for file in `find ${OUR_COPY} -name '*.py'`; do
    # change all of the starlette imports to prefect._vendor.starlette
    sed -i -e 's/from starlette/from prefect._vendor.starlette/g' $file
    sed -i -e 's/import starlette/import prefect._vendor.starlette/g' $file
    # change all of the fastapi imports to prefect._vendor.fastapi
    sed -i -e 's/from fastapi/from prefect._vendor.fastapi/g' $file
    sed -i -e 's/import fastapi/import prefect._vendor.fastapi/g' $file
    # change all of the fastapi_users imports to prefect._vendor.fastapi_users
    sed -i -e 's/from fastapi_users/from prefect._vendor.fastapi_users/g' $file
    sed -i -e 's/import fastapi_users/import prefect._vendor.fastapi_users/g' $file
    # change all of the httpx_oauth imports to prefect._vendor.httpx_oauth
    sed -i -e 's/from httpx_oauth/from prefect._vendor.httpx_oauth/g' $file
    sed -i -e 's/import httpx_oauth/import prefect._vendor.httpx_oauth/g' $file
done
