#!/bin/bash
VERSION=$1
OUR_COPY=src/prefect/_vendor/fastapi_users

rm -Rf /tmp/fastapi_users
git clone https://github.com/fastapi-users/fastapi-users -b $VERSION /tmp/fastapi_users
rsync -ravP --delete /tmp/fastapi_users/fastapi_users/ $OUR_COPY

for file in `find ${OUR_COPY} -name '*.py'`; do
    # change all of the fastapi imports to prefect._vendor.fastapi
    sed -i -e 's/from fastapi/from prefect._vendor.fastapi/g' $file
    sed -i -e 's/import fastapi/import prefect._vendor.fastapi/g' $file
    # change all of the fastapi_users imports to prefect._vendor.fastapi_users
    sed -i -e 's/from fastapi_users/from prefect._vendor.fastapi_users/g' $file
    sed -i -e 's/import fastapi_users/import prefect._vendor.fastapi_users/g' $file
    # change all of the httpx_oauth imports to prefect._vendor.httpx_oauth
    sed -i -e 's/from httpx_oauth/from prefect._vendor.httpx_oauth/g' $file
    sed -i -e 's/import httpx_oauth/import prefect._vendor.httpx_oauth/g' $file
done
