import os

PREFECT_AUTH_OIDC_CLIENT_ID = os.environ["PREFECT_AUTH_OIDC_CLIENT_ID"]
PREFECT_AUTH_OIDC_CLIENT_SECRET = os.environ["PREFECT_AUTH_OIDC_CLIENT_SECRET"]
PREFECT_AUTH_OIDC_URL = os.environ["PREFECT_AUTH_OIDC_URL"]
PREFECT_AUTH_SECRET = os.environ["PREFECT_AUTH_SECRET"]
PREFECT_AUTH_COOKIE_NAME = os.environ.get(
    "PREFECT_AUTH_COOKIE_NAME", "prefect"
)
PREFECT_AUTH_COOKIE_MAX_AGE = int(
    os.environ.get("PREFECT_AUTH_COOKIE_MAX_AGE", 60 * 60 * 24)
)
